# golangci-lint configuration
run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - .git
    - bin
    - tmp
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  
  golint:
    min-confidence: 0.8
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/Abhiro0p/stories-backend
  
  misspell:
    locale: US
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint
      - unnamedResult

  cyclop:
    max-complexity: 15
    
  funlen:
    lines: 80
    statements: 50

  goconst:
    min-len: 3
    min-occurrences: 3

  revive:
    rules:
      - name: exported
        disabled: false
        arguments: ["checkPrivateReceivers", "disableStutteringCheck"]

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - goconst
    - gocritic
    - revive
    - cyclop
    - funlen
    - gocognit
    - dupl
    - gosec
    - unconvert
    - exportloopref
    - nilerr
    - nolintlint
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocognit
        - errcheck
        - dupl
        - gosec
        - funlen

    # Exclude known linters from partially hard-to-fix issues
    - linters:
        - gosec
      text: "G404:" # Use of weak random number generator

    # Exclude duplicate code detection in auto-generated files
    - linters:
        - dupl
      path: ".*\\.pb\\.go$"

  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: ""
