run:
  timeout: 5m
  modules-download-mode: readonly


linters:
  enable:
    - gofmt
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - deadcode
    - varcheck
  disable:
    - errcheck
