apiVersion: v1
kind: ConfigMap
metadata:
  name: stories-backend-config
  namespace: stories-backend
  labels:
    app: stories-backend
data:
  # Server configuration
  PORT: "8080"
  GIN_MODE: "release"
  API_PREFIX: "/api/v1"
  
  # MinIO configuration
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_BUCKET: "stories-media"
  MINIO_USE_SSL: "false"
  MINIO_REGION: "us-east-1"
  PRESIGNED_URL_EXPIRY_MINUTES: "15"
  
  # JWT configuration
  JWT_EXPIRY_HOURS: "1"
  JWT_REFRESH_EXPIRY_DAYS: "7"
  JWT_ISSUER: "stories-backend"
  JWT_AUDIENCE: "stories-app"
  
  # Rate limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "120"
  RATE_LIMIT_BURST: "20"
  
  # CORS configuration
  CORS_ENABLED: "true"
  CORS_ALLOWED_ORIGINS: "https://yourdomain.com,https://www.yourdomain.com"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  CORS_ALLOWED_HEADERS: "Origin,Content-Type,Accept,Authorization,X-Requested-With"
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_MAX_AGE: "86400"
  
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  LOG_OUTPUT: "stdout"
  LOG_ENABLE_CALLER: "true"
  
  # Worker configuration
  WORKER_POLL_INTERVAL: "30s"
  WORKER_BATCH_SIZE: "200"
  WORKER_MAX_RETRIES: "3"
  WORKER_TIMEOUT: "300s"
  
  # Feature flags
  FEATURE_STORY_REACTIONS: "true"
  FEATURE_STORY_VIEWS: "true"
  FEATURE_USER_FOLLOW: "true"
  FEATURE_REAL_TIME_NOTIFICATIONS: "true"
  FEATURE_ANALYTICS: "true"
  FEATURE_MEDIA_UPLOAD: "true"
  
  # Prometheus configuration
  PROMETHEUS_ENABLED: "true"
  PROMETHEUS_PORT: "9090"
  PROMETHEUS_PATH: "/metrics"
  
  # Cache configuration
  CACHE_TTL_USER: "300s"
  CACHE_TTL_STORY: "180s"
  CACHE_TTL_FEED: "60s"
  CACHE_TTL_ANALYTICS: "900s"
  
  # Database configuration
  DB_MAX_OPEN_CONNS: "100"
  DB_MAX_IDLE_CONNS: "25"
  DB_MAX_LIFETIME: "3600s"
  
  # Redis configuration
  REDIS_DB: "0"
  REDIS_POOL_SIZE: "20"
  REDIS_MIN_IDLE_CONNS: "10"
  REDIS_IDLE_TIMEOUT: "300s"
