apiVersion: apps/v1
kind: Deployment
metadata:
  name: stories-backend-api
  namespace: stories-backend
  labels:
    app: stories-backend-api
    version: "1.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: stories-backend-api
  template:
    metadata:
      labels:
        app: stories-backend-api
        version: "1.0.0"
    spec:
      containers:
      - name: stories-api
        image: ghcr.io/your-username/stories-backend-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: PORT
          value: "8080"
        - name: GIN_MODE
          value: "release"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: stories-backend-secret
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: stories-backend-secret
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: stories-backend-secret
              key: jwt-secret
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: stories-backend-config
              key: minio-endpoint
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: stories-backend-secret
              key: minio-access-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: github-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stories-backend-worker
  namespace: stories-backend
  labels:
    app: stories-backend-worker
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stories-backend-worker
  template:
    metadata:
      labels:
        app: stories-backend-worker
        version: "1.0.0"
    spec:
      containers:
      - name: stories-worker
        image: ghcr.io/your-username/stories-backend-worker:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: stories-backend-secret
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: stories-backend-secret
              key: redis-url
        - name: WORKER_POLL_INTERVAL
          value: "30s"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: github-registry
