groups:
- name: stories-backend-recording-rules
  interval: 30s
  rules:
  # Request rate
  - record: stories:http_requests:rate5m
    expr: rate(http_requests_total[5m])

  # Error rate
  - record: stories:http_errors:rate5m
    expr: rate(http_requests_total{status_code=~"5.."}[5m])

  # Response time percentiles
  - record: stories:http_response_time:p95
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))

  - record: stories:http_response_time:p99
    expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))

  # Database metrics
  - record: stories:db_connections:utilization
    expr: database_connections_active / database_connections_max

  # Redis metrics
  - record: stories:redis_memory:utilization
    expr: redis_memory_used_bytes / redis_memory_max_bytes

  # Story metrics
  - record: stories:story_creation:rate1m
    expr: rate(stories_created_total[1m])

  - record: stories:story_views:rate1m
    expr: rate(stories_viewed_total[1m])

  # User activity
  - record: stories:active_users:5m
    expr: count(rate(http_requests_total[5m]) > 0)
